#pragma once

#define SKIPPER_SKEETO_1_1 0
#define SKIPPER_SKEETO_1_2 1
#define SKIPPER_SKEETO_2 2

#define DATA_TYPE_RAW 0
#define DATA_TYPE_GRAPH 1

#define USED_DATA_TYPE DATA_TYPE_RAW
#define GAME_VERSION SKIPPER_SKEETO_1_1

#define THREAD_COUNT 8
#define POOL_TOTAL_BYTES 4000000000
#define POOL_COUNT (POOL_TOTAL_BYTES / (THREAD_COUNT * sizeof(GraphPath)))

#define TEMP_DIR "temp"
#define TEMP_PATHS_DIR TEMP_DIR "/paths"
#define TEMP_STATES_DIR TEMP_DIR "/states"

#if GAME_VERSION == SKIPPER_SKEETO_1_1

#define FILE_IDENTIFIER "1-1"
#define SCENE_COUNT 43
#define ITEM_COUNT 28
#define TASK_COUNT 26
#define STATE_SCENE_INDEX_SIZE 6
#define STATE_TASK_ITEM_START STATE_SCENE_INDEX_SIZE
#define STATE_TASK_ITEM_SIZE 45

#if USED_DATA_TYPE == DATA_TYPE_RAW

#error Configuration not supported

#elif USED_DATA_TYPE == DATA_TYPE_GRAPH

#define VERTICES_COUNT 39
#define EDGES_COUNT 205

#endif

#elif GAME_VERSION == SKIPPER_SKEETO_1_2

#define FILE_IDENTIFIER "1-2"
#define SCENE_COUNT 44
#define ITEM_COUNT 39
#define TASK_COUNT 32
#define STATE_SCENE_INDEX_SIZE 6
#define STATE_TASK_ITEM_START STATE_SCENE_INDEX_SIZE
#define STATE_TASK_ITEM_SIZE 55
#define FOUND_BEST_DISTANCE 82

#if USED_DATA_TYPE == DATA_TYPE_RAW

#define VERTICES_COUNT STATE_TASK_ITEM_SIZE
#define EDGES_COUNT 250

#elif USED_DATA_TYPE == DATA_TYPE_GRAPH

#define VERTICES_COUNT 45
#define EDGES_COUNT 227

#endif

#elif GAME_VERSION == SKIPPER_SKEETO_2

#define FILE_IDENTIFIER "2"
#define SCENE_COUNT 28
#define ITEM_COUNT 29
#define TASK_COUNT 21
#define STATE_SCENE_INDEX_SIZE 6
#define STATE_TASK_ITEM_START STATE_SCENE_INDEX_SIZE
#define STATE_TASK_ITEM_SIZE 39

#if USED_DATA_TYPE == DATA_TYPE_RAW

#define VERTICES_COUNT STATE_TASK_ITEM_SIZE
#define EDGES_COUNT 154

#elif USED_DATA_TYPE == DATA_TYPE_GRAPH

#error Configuration not supported

#endif

#endif
